version: "3.9"

services:
  php:
    build:
      context: .
      target: php_dev
    environment:
      XDEBUG_MODE: "off"
      XDEBUG_CONFIG: >-
        client_host=host.docker.internal
        client_port=9003
        idekey=PHPSTORM
      PHP_IDE_CONFIG: "serverName=lexoffice-sdk"
      PS1: "[lexoffice-sdk]::$$(pwd) # "
    volumes:
      - ./:/srv/php:rw,cached
    extra_hosts:
      - "host.docker.internal:host-gateway"
