name: "security-check"

on:
  pull_request:
  schedule:
    - cron: '0 12 * * *'

jobs:
  security-check:
    name: security-check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: The PHP Security Checker
        uses: symfonycorp/security-checker-action@v5
        id: security-check
        with:
          lock: composer.lock
